### ISSUE TITLE
Bug: addDataChangeListener constantly firing

### ISSUE THREAD

**Issue by KR155E** [hunkim98/dotting#101]
I added a callback to the addDataChangeListener and noticed that it was constantly firing, even when absolutely no user interaction took place.

**Comment by hunkim98** [comment]
Could you give me the details on how you implemented `addDataChangeListener` to your project? More context would greatly help me understand the issue.

**Comment by KR155E** [comment]
It looks like I made a mistake here. I reimplemented the change listener as demonstrated in [DataChangeListener.tsx](https://github.com/hunkim98/dotting/blob/main/stories/useHandlersComponents/DataChangeListener.tsx) and this time it worked flawlessly. Thanks again!

**Comment by hunkim98** [comment]
Great!
