### ISSUE TITLE
Feature request: add additional tools, e.g. line drawing tools

### ISSUE THREAD

**Issue by KR155E** [hunkim98/dotting#103]
The tools already implemented in dotting are great and totally workable with. However, it would be awesome to see some more standard tools being implemented like a stroke/line drawing tool or (filled/not filled) rectangle and circle drawing tools. Are there plans for this?

**Comment by hunkim98** [comment]
Yes there were plans for implementing this in the past, however, we could not finish implementing them. Creating a new tool takes some time, but I will try my best to at least create a stroke drawing tool at least!

**Comment by hunkim98** [comment]
@tjrwodnjs is likely going to work on this issue!🙏
