### ISSUE TITLE
Proposal: minimum grid scale parameter

### ISSUE THREAD

**Issue by KR155E** [hunkim98/dotting#97]
Thank you very much for this package, @hunkim98! It's exactly what I have been looking for to create a pixel art editor with for my custom IDE. Doing a test implementation, I have come across a few issues and also some ideas for improvement, which I would like to share (and will create separate tickets for). Let me start with the following feature request.

When zooming out of your image, the grid takes up more and more space in relation to the actual pixels. At a certain scale, one can no longer make out the pixels at all, but only sees the grid. This becomes more apparent the bigger the image gets.

To solve this, I propose a parameter (perhaps called gridMinimumScale), which allows to set a minimum scale below which the grid gets automatically disabled.

<img width="210" alt="Bildschirmfoto 2024-01-18 um 11 50 17" src="https://github.com/hunkim98/dotting/assets/2768706/b357db03-6e68-40fd-ab8b-06e156917ff5">

**Comment by hunkim98** [comment]
@KR155E Thank you for your interest in our package! It is great that you are considering to use this library for your custom IDE. I would love to hear more about the IDE you are planning to create later on. 

I also had similar thoughts on your proposal to make the grid invisible when the canvas is zoomed out to a certain level. I will definitely implement this as soon as I can. I am thinking of setting the gridMinimumScale inside the component directly (Users will not be able to set this gridMinimumScale). 

I will look into other issues you have opened one by one. If there is an issue that you would like to solve on your own or need some explanation, please feel free to tag me.😃

**Comment by KR155E** [comment]
That is great to hear, @hunkim98, thanks for your feedback. 

The IDE I mentioned is called [VUEngine Studio](https://www.vuengine.dev/) and is designed specifically for Nintendo Virtual Boy homebrew development with our own game engine. I would love to have an embedded pixel art editor to allow people to create graphical game assets in the right format right in the IDE, without having to rely on external graphic programs. Here's a screenshot of my current implementation of dotting.

<img width="1359" alt="Bildschirmfoto 2024-01-18 um 13 02 43" src="https://github.com/hunkim98/dotting/assets/2768706/11c869ca-f92d-4158-9d20-f3e8d464ca57">

**Comment by hunkim98** [comment]
Fascinating! I will give you updates on your requested features as I solve them one by one! I will definitely try your IDE too.
